TravelXWeb/TravelXWeb/Controllers/HotelController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TravelXWeb.DataManager;
using TravelXWeb.ViewModel;

namespace TravelXWeb.Controllers
{
    [Authorize]
    public class HotelController : Controller
    {
        readonly log4net.ILog logger = log4net.LogManager.GetLogger(System.Reflection.MethodBase.GetCurrentMethod().DeclaringType);
        // GET: Hotel
        public ActionResult Index()
        {
            HotelIndexViewModelList vm = HotelDataManager.GetAllHotelForIndexView();
            return View(vm);
        }

        // GET: Hotel/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: Hotel/Create
        public ActionResult Create()
        {
            try
            {
                HotelCreateViewModel viewModel = new HotelCreateViewModel();
                viewModel = HotelDataManager.GetHotelCreateViewModel();
                return View(viewModel);
            }
            catch (Exception ex)
            {
                logger.Error("User Create Page Load", ex);
                return View("Error");
            }
        }

        // POST: Hotel/Create
        [HttpPost]
        public ActionResult Create(HotelCreateViewModel viewModel)
        {
            
            // TODO: Add insert logic here
            var result = HotelDataManager.HotelCreateViewModel(viewModel);
            if (result.IsSuccessful)
            {
                return RedirectToAction("Index");
            }
            else
            {
                //return ModelState.AddModelError("HotelAgent", result.ExceptionObject != null ? result.ExceptionObject.ToString() : result.ErrorMessage);
                return View("Error");
            }
        }

        // GET: Hotel/Edit/5
        public ActionResult Edit(int id)
        {
            HotelIndexEditViweModel vm = new HotelIndexEditViweModel();
            vm=HotelDataManager.GetHotelForEdit(id);
            ViewBag.Latittude = vm.Latitude;
            ViewBag.Longitude = vm.Longitude;
            return View(vm);
        }

        // POST: Hotel/Edit/5
        [HttpPost]
        public ActionResult Edit(HotelIndexEditViweModel viewModel)
        {         
            // TODO: Add insert logic here
            var result = HotelDataManager.HotelEdit(viewModel);
            if (result.IsSuccessful)
            {
                return RedirectToAction("Index");
            }
            else
            {
                //return ModelState.AddModelError("HotelAgent", result.ExceptionObject != null ? result.ExceptionObject.ToString() : result.ErrorMessage);
                return View("Error");
            }
        }

        // GET: Hotel/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Hotel/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        public ActionResult HotelImageDelete(int hotelImageId)
        {
            var result = HotelDataManager.HotelImageDelete(hotelImageId);
            return Json(result,JsonRequestBehavior.AllowGet);
        }
    }
}

TravelXWeb/TravelXWeb/Controllers/RoomController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TravelXWeb.DataManager;
using TravelXWeb.TravelXDataBaseModel;
using TravelX.ViewModel;

namespace TravelXWeb.Controllers
{
    [Authorize]
    public class RoomController : Controller
    {
        readonly log4net.ILog logger = log4net.LogManager.GetLogger(System.Reflection.MethodBase.GetCurrentMethod().DeclaringType);

        // GET: Room
        public ActionResult Index()
        {
            HotelAgentViewModel vm = new HotelAgentViewModel();
            vm = HotelAgentDataManager.IndexHotelAgent();
            return View(vm);
        }

        // GET: Room/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: Room/Create
        public ActionResult Create()
        {
            try
            {
                HotelAgentCreateViewModel viewModel = new HotelAgentCreateViewModel();
                viewModel = HotelAgentDataManager.GetHotelAgentCreateViewModel();
                return View(viewModel);
            }
            catch (Exception ex)
            {
                logger.Error("User Create Page Load", ex);
                return View("Error");
            }
        }

        // POST: Room/Create
        [HttpPost]
        public ActionResult Create(HotelAgentCreateViewModel viewModel)
        {
            // TODO: Add insert logic here
            var result = HotelAgentDataManager.CreateHotelAgent(viewModel);
            if (result.IsSuccessful)
            {
                return RedirectToAction("Index");
            }
            else
            {
                //return ModelState.AddModelError("HotelAgent", result.ExceptionObject != null ? result.ExceptionObject.ToString() : result.ErrorMessage);
                return View("Error");
            }
        }

        // GET: Room/Edit/5
        public ActionResult Edit(int id)
        {
            HotelAgentEditViewModel vm= new HotelAgentEditViewModel();
            vm = HotelAgentDataManager.GetHotelAgentForEdit(id);
            return View(vm);
        }

        // POST: Room/Edit/5
        [HttpPost]
        public ActionResult Edit(HotelAgentEditViewModel viewModel)
        {
            // TODO: Add insert logic here
            var result = HotelAgentDataManager.HotelAgentEdit(viewModel);
            if (result.IsSuccessful)
            {
                return RedirectToAction("Index");
            }
            else
            {
                //return ModelState.AddModelError("HotelAgent", result.ExceptionObject != null ? result.ExceptionObject.ToString() : result.ErrorMessage);
                return View("Error");
            }
        }

        // GET: Room/Delete/5
        public ActionResult Delete(int id)
        {
            var result = HotelAgentDataManager.HotelAgentDelete(id);
            if (result.IsSuccessful)
            {
                return RedirectToAction("Index");
            }
            else
            {
                //return ModelState.AddModelError("HotelAgent", result.ExceptionObject != null ? result.ExceptionObject.ToString() : result.ErrorMessage);
                return View("Error");
            }
        }

        // POST: Room/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

TravelXWeb/TravelXWeb/Controllers/UserController.cs
using System;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.Owin;
using TravelXWeb.DataManager;
using TravelXWeb.Models;
using TravelX.ViewModel;
using TravelXWeb.TravelXDataBaseModel;
using TravelXWeb.ViewModel;


namespace TravelXWeb.Controllers
{
    //[Authorize(Roles = "SystemAdministrator, AccountAdministrator, VenueAdministrator")]
    public class UserController : BaseController
    {
        readonly log4net.ILog logger = log4net.LogManager.GetLogger(System.Reflection.MethodBase.GetCurrentMethod().DeclaringType);

        private ApplicationUserManager _userManager;
        private ApplicationSignInManager _signInManager;

        public UserController()
        {
        }
        public UserController(ApplicationUserManager userManager, ApplicationSignInManager signInManager)
        {
            UserManager = userManager;
            SignInManager = signInManager;
        }

        public ApplicationUserManager UserManager
        {
            get
            {
                return _userManager ?? HttpContext.GetOwinContext().GetUserManager<ApplicationUserManager>();
            }
            private set
            {
                _userManager = value;
            }
        }
        public ApplicationSignInManager SignInManager
        {
            get
            {
                return _signInManager ?? HttpContext.GetOwinContext().Get<ApplicationSignInManager>();
            }
            private set
            {
                _signInManager = value;
            }
        }
        TravelXEntities db = new TravelXEntities();
        // GET: User
        public ActionResult Index(int? page)
        {
            //var userViewModelList = from user in db.AspNetUsers select user;
            var userViewModelList = UserDataManager.GetAllUserForVIew();
            //if (!String.IsNullOrEmpty(searchString))
            //{
            //    webUsers = userViewModelList.Where(l => l.FirstName.Contains(searchString) || l.LastName.Contains(searchString));
            //}
            int pageSize = 5;
            int pageNumber = (page.HasValue ? page.Value : 1);
            ViewBag.PageNumber = pageNumber;
            ViewBag.PageSize = pageSize;
            return View(userViewModelList);

            //return View();
        }

        public ActionResult DashBoardSummery()
        {
            return View();
        }

        public ActionResult UserProfile()
        {
            int userId = (int)(System.Web.HttpContext.Current.Session["UserId"]);
            UserProfile uerProfile = UserDataManager.GetUserProfile(userId);                
            return View(uerProfile);
        }

        //
        // GET: /Account/Login
        [AllowAnonymous]
        public ActionResult Login(string returnUrl)
        {
            ViewBag.ReturnUrl = returnUrl;
            return View();
        }

        //
        // POST: /Account/Login
        [HttpPost]
        [AllowAnonymous]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Login(UserLoginViewModel model, string returnUrl)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }

            // This doesn't count login failures towards account lockout
            // To enable password failures to trigger account lockout, change to shouldLockout: true
            var result = await SignInManager.PasswordSignInAsync(model.UserName, model.Password, model.RememberMe, shouldLockout: false);
            //ApplicationUser currentUser = UserManager.FindByName(User.Identity.Name);
            //if (currentUser != null && currentUser.Roles.Any())
            //{
            //    Session["UserId"] = currentUser.Id;
            //    Session["UserFirstLastName"] = currentUser.FirstName + " " + currentUser.LastName;
            //    var roles = currentUser.Roles.ToList();
            //    var identityUserRole = roles.FirstOrDefault();
            //    if (identityUserRole != null)
            //    {
            //        Session["UserRoleId"] = identityUserRole.RoleId;
            //    }
            //    //return RedirectToLocal(returnUrl);
            //    return RedirectToAction("Index");
            //}
            //ModelState.AddModelError("", "Invalid login attempt.");
            //return View(model);
            //ApplicationUser currentUser = UserManager.FindByName(User.Identity.Name);

            switch (result)
            {
                case SignInStatus.Success:
                    return RedirectToAction("DashBoardSummery"); ;
                case SignInStatus.LockedOut:
                    return View("Lockout");
                case SignInStatus.RequiresVerification:
                    return RedirectToAction("SendCode", new { ReturnUrl = returnUrl, RememberMe = false });
                case SignInStatus.Failure:
                default:
                    ModelState.AddModelError("", "Invalid login attempt.");
                    return View(model);
            }
        }

        private ActionResult RedirectToLocal(string returnUrl)
        {
            if (Url.IsLocalUrl(returnUrl))
            {
                return Redirect(returnUrl);
            }
            return RedirectToAction("Index", "Home");
        }

        // GET: User/Details/5
        //public ActionResult Details(int id)
        //{
        //    return View();
        //}

        [Authorize]
        //GET: User/Create
        public ActionResult Create()
        {
            try
            {
                //var currUser = UserManager.FindById(User.Identity.GetUserId());
                UserCreateViewModel ucvm = new UserCreateViewModel();
                ucvm.systemRole = db.AspNetRoles.ToList();
                return View(ucvm);
            }
            catch (Exception ex)
            {
                logger.Error("User Create Page Load", ex);
                return View("Error");
            }

        }

        // POST: User/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(UserCreateViewModel userViewModel)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    // TODO: Add insert logic here
                    var user = new ApplicationUser {FirstName = userViewModel.FirstName, LastName = userViewModel.LastName, UserName = userViewModel.UserName, Email = userViewModel.Email, PhoneNumber = userViewModel.PhoneNumber, Address = userViewModel.Address,IsActive = true,IsDelete = false,CreatedBy = (int)(System.Web.HttpContext.Current.Session["UserId"]), CreatedDate = DateTime.Now,UpdatedBy = default(int),UpdateDate = null};
                    //var user = new ApplicationUser {FirstName = userViewModel.FirstName, LastName = userViewModel.LastName, UserName = userViewModel.UserName, Email = userViewModel.Email, PhoneNumber = userViewModel.PhoneNumber, Address = userViewModel.Address,IsActive = true,IsDelete = false,CreatedBy = 1, CreatedDate = DateTime.Now,UpdatedBy = default(int),UpdateDate = null};
                    user.Roles.Add(new CustomUserRole() { UserId = user.Id, RoleId = userViewModel.RoleId});                    
                    var result = await UserManager.CreateAsync(user, userViewModel.Password);
                    if (result.Succeeded)
                    {
                        return RedirectToAction("Index");                      
                    }
                    string errors = ((string[])result.Errors)[0];
                    ModelState.AddModelError("", errors);
                    //AddErrors(result);
                    return View(userViewModel);
                }
                return View(userViewModel);
            }
            catch (Exception ex)
            {
                logger.Error("Create User Error", ex);
                return View("Error");
            }
        }

        // GET: User/Edit/5
        public ActionResult Edit(int Id)
        {

            UserUpdateViewModel ucvm = new UserUpdateViewModel();
            ucvm = UserDataManager.GetUserByIdForUpdate(Id);
            ucvm.systemRole = db.AspNetRoles.ToList();
            return View(ucvm);
        }

        // POST: User/Edit/5
        [HttpPost]
        public ActionResult Edit(UserUpdateViewModel ucvm)
        {
            try
            {
                // TODO: Add update logic here
                bool result = UserDataManager.UpdateUser(ucvm);
                if (result == true)
                {
                    return RedirectToAction("Index");
                }
                return View(ucvm);
            }
            catch (Exception ex)
            {
                logger.Error("Edit User Error", ex);
                return View("Error");
            }
        }

        // GET: User/Delete/5
        public ActionResult Delete(string id)
        {
            try
            {
                bool result = UserDataManager.DeleteUser(id);
                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                logger.Error("Edit User Error", ex);
                return View("Error");
            }
        }

        // POST: User/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        public ActionResult UserSetting()
        {
            UserSetting us = new UserSetting();
            return View(us);
        }        

TravelXWeb/TravelXWeb/Views/Shared/_AdminLayout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Admin Panel : TravelX</title>
    <!-- FAVICON -->
    <link rel="shortcut icon" type="/image/png" href="/img/favicon.png" />
    <!-- Bootstrap Styles-->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <!-- FontAwesome Styles-->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <!-- TABLE STYLES-->
    <link href="~/AdminCssJs/css/dataTables.bootstrap.css" rel="stylesheet" />
    <!-- DATEPICKER STYLES-->
    <link rel="stylesheet" type="text/css" href="~/AdminCssJs/css/datepicker/datepicker.css">
    <!-- Custom Styles-->
    <link href="~/AdminCssJs/css/custom-styles.css" rel="stylesheet" />
    <!-- Google Fonts-->
    <link href='http://fonts.googleapis.com/css?family=Open+Sans' rel='stylesheet' type='text/css' />
    @*@Styles.Render("~/Content/css")
        @Scripts.Render("~/bundles/modernizr")*@
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/jqueryval")
    @RenderSection("scripts", required: false)

</head>
<body>
    <div class="container" id="wrapper">
        <div class="row main-row" style="">
            <nav class="navbar navbar-default top-navbar" role="navigation">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".sidebar-collapse">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href='@Url.Action("Index", "User")'>TravelX</a>
                </div>
                <ul class="nav navbar-top-links navbar-right">
                    <li id="usprofile" class="dropdown applydropdown">
                        <a class="dropdown-toggle" data-toggle="dropdown" href="#" aria-expanded="false">
                            <i class="fa fa-user fa-fw"></i> <i class="fa fa-caret-down"></i>
                        </a>
                        <ul class="dropdown-menu dropdown-user">
                            <li>
                                <a href='@Url.Action("UserProfile", "User")'><i class="fa fa-user fa-fw"></i> User Profile</a>
                            </li>
                            <li>
                                <a href='@Url.Action("UserSetting", "User")'><i class="fa fa-gear fa-fw"></i> Settings</a>
                            </li>
                            <li class="divider"></li>
                            <li>
                                <a href='@Url.Action("LogOff", "Account")'><i class="fa fa-sign-out fa-fw"></i> Logout</a>
                            </li>
                        </ul>
                        <!-- /.dropdown-user -->
                    </li>
                    <!-- /.dropdown -->
                </ul>
            </nav>
        </div>
        <!--/. NAV TOP -->
        <nav class="navbar-default navbar-side" role="navigation">
            <div class="sidebar-collapse">
                <ul class="nav" id="main-menu">
                    <li>
                        <a class="active-menu" href='@Url.Action("DashBoardSummery","User")'><i class="fa fa-dashboard"></i> Dashboard</a>
                    </li>
                    <li>
                        <a class="" href='@Url.Action("Index","Hotel")'><i class="fa fa-qrcode"></i> Manage Hotels</a>
                    </li>
                    <li>
                        <a class="" href='@Url.Action("Index","Room")'><i class="fa fa-fw fa-file"></i> Manage Hotel Rooms </a>
                    </li>
                    <li>
                        <a class="" href='@Url.Action("Index","User")'><i class="fa fa-table"></i> Manage Users</a>
                    </li>
                </ul>
            </div>
        </nav>
        <!-- /. NAV SIDE -->
        <div id="page-wrapper">
            <div id="page-inner">
                @RenderBody()
                <!-- /. ROW -->
                <footer>
                    <p>All right reserved.</p>
                </footer>
            </div>
            <!-- /. PAGE INNER -->
        </div>
        <!-- /. PAGE WRAPPER -->
    </div>
    @*@Scripts.Render("~/bundles/jquery")
        @Scripts.Render("~/bundles/bootstrap")*@
    @*@RenderSection("scripts", required: false)*@
</body>
</html>
  
<Script>

        $(document).ready(function (){
            $('#usprofile').click(function () {
            $(this).closest('li').addClass('open');
        });
    });

</Script>

TravelXWeb/TravelXWeb/Views/Shared/_HotelImages.cshtml
@using TravelXWeb.ViewModel
@model IEnumerable<TravelXWeb.ViewModel.HotelImageListForEdit>

<div class="modal fade" id="hotelImagesMpdal" data-backdrop="static" data-keyboard="false">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header orange-modal-heading">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h2 class="modal-title">
                    <span class="glyphicon glyphicon-picture">&nbsp;</span>Hotel Images
                </h2>
            </div>
            <div class="modal-body">
                @foreach (var item in Model)
                {
                    <div class="form-group">
                        <img style="width: 200px;height: 200px" src="@Url.Content("~/img/HotelImages/" + System.IO.Path.GetFileName(item.ImagePath))" alt="Image Not Found" />
                        @*<div id="HotelImageId1" data-id="@item.HotelImageId" class="custom">@item.ImagePath</div>*@
                        <span class="remove_img_add" id="HotelImageId" data-myval="@item.HotelImageId">x</span>
                    </div>

                }
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-danger" data-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>

<script>
    $(".remove_img_add")
        .click(function () {
            var element = $(this).prev();
            var hotelImageId = $('#HotelImageId').data('myval');
            //alert(hotelImageId);
            element.hide();
            $(this).hide();
            $.ajax({
                url: '/Hotel/HotelImageDelete',
                type: "POST",
                datatype: "JSON",
                async: false,
                data: { hotelImageId: hotelImageId },
                success: function (response) {
                    if (response === true)
                        alert('Image deleted successfully');
                    else {
                        alert('There is error.Please contact to system admin');
                    }
                }

            });

        });
</script>

TravelXWeb/TravelXWeb/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <!-- SITE TITTLE -->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>@ViewBag.Title - TravelX</title>
    <!-- PLUGINS CSS STYLE -->
    <link href="~/Content/PluginBootstrap/jquery-ui/jquery-ui.css" rel="stylesheet">
    <link href="~/Content/PluginBootstrap/css/bootstrap.min.css" rel="stylesheet">
    <link href="~/Content/PluginBootstrap/font-awesome/css/font-awesome.min.css" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="~/Content/PluginBootstrap/rs-plugin/css/settings.css" media="screen">
    <link rel="stylesheet" type="text/css" href="~/Content/PluginBootstrap/selectbox/select_option1.css">
    <link rel="stylesheet" type="text/css" href="~/Content/PluginBootstrap/datepicker/datepicker.css">
    <link rel="stylesheet" type="text/css" href="~/Content/PluginBootstrap/isotope/jquery.fancybox.css">
    <link rel="stylesheet" type="text/css" href="~/Content/PluginBootstrap/isotope/isotope.css">


    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="~/Content/PluginBootstrap/jquery-ui/jquery-ui.js"></script>
    <script src="~/Content/PluginBootstrap/bootstrap/js/bootstrap.min.js"></script>
    <script src="~/Content/PluginBootstrap/rs-plugin/js/jquery.themepunch.tools.min.js"></script>
    <script src="~/Content/PluginBootstrap/rs-plugin/js/jquery.themepunch.revolution.min.js"></script>
    <script src="~/Content/PluginBootstrap/selectbox/jquery.selectbox-0.1.3.min.js"></script>
    <script src="~/Content/PluginBootstrap/datepicker/bootstrap-datepicker.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/waypoints/2.0.3/waypoints.min.js"></script>
    <script src="~/Content/PluginBootstrap/counter-up/jquery.counterup.min.js"></script>
    <script src="~/Content/PluginBootstrap/isotope/isotope.min.js"></script>
    <script src="~/Content/PluginBootstrap/isotope/jquery.fancybox.pack.js"></script>
    <script src="~/Content/PluginBootstrap/isotope/isotope-triger.js"></script>
    <script src="~/Content/PluginBootstrap/countdown/jquery.syotimer.js"></script>
    <script src="~/SiteJs/custom.js"></script>


    <!-- GOOGLE FONT -->
    <link href='https://fonts.googleapis.com/css?family=Montserrat:400,600,700' rel='stylesheet' type='text/css'>
    <!-- CUSTOM CSS -->
    @*<link href="css/style.css" rel="stylesheet">*@
    <link href="~/Content/style.css" rel="stylesheet" />
    @*<link rel="stylesheet" href="css/colors/default.css" id="option_color">*@
    <link href="~/Content/colors/default.css" rel="stylesheet" />
    <!-- FAVICON -->
    <link rel="shortcut icon" type="/image/png" href="/img/favicon.png" />
    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
    @*@Styles.Render("~/Content/css")
        @Scripts.Render("~/bundles/modernizr")*@
    @RenderSection("scripts", required: false)
</head>
<body>
   @Html.Partial("_LayoutHeader");  @*difference between rendersection and @Html.partial*@
    <div>
        @RenderBody()
        @*<hr />
            <footer>
                <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
            </footer>*@
    </div>
    @Html.Partial("_LayoutFooter");
    @*@Scripts.Render("~/bundles/jquery")
        @Scripts.Render("~/bundles/bootstrap")
        @RenderSection("scripts", required: false)*@
</body>
</html>